decoration {
    rounding = 5

    shadow {
      enabled = true
      range = 15
      render_power = 1
      color = 0x55000000
      color_inactive = 0x55000000
      offset = 0 4
      ignore_window = 1
    }

    blur {
      enabled = true
      size = 6
      passes = 2
      new_optimizations = 1
      xray = 1
    }
}
