# gen
bind = SUPER, Q, killactive
bind = SUPER, E, exit
bind = SUPER, S, togglefloating
bind = SUPER, UP, togglesplit,
bind = SUPER, U, exec, pactl set-sink-volume @DEFAULT_SINK@ +10%
bind = SUPER CTRL, U, exec, pactl set-sink-volume @DEFAULT_SINK@ -10% 
bind = SUPER CTRL, L, exec, loginctl suspend

# wallpaper
bind = SUPER, B, exec, ~/apps-config/config/hypr/scripts/wallpaper/wallpaper_picker

# misc
bind = SUPER SHIFT, P, pseudo
bind = , PRINT, exec, ~/apps-config/config/hypr/scripts/default/screenshot selection
bind = CTRL, PRINT, exec, ~/apps-config/config/hypr/scripts/default/screenshot full_screen

bind = SUPER CTRL, A, exec, hyprctl dispatch fullscreen 1
bind = SUPER SHIFT, A, exec, hyprctl dispatch fullscreen 2

bind = SUPER CTRL, C, exec, hyprpicker -a && notify-send -u critical -t 4000 "$(wl-paste)"
