#!/bin/sh

hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/wallpapers

wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/scripts/scripts/wallpaper

# echo "~/.config/hypr/wallpapers$wallpaper"
# swaybg -m fill -i "$HOME/.config/hypr/wallpapers/$wallpaper" &
