#!/bin/bash

source "$HOME/apps-config/config/hypr/scripts/variables/load_envs"

function load_wp(){
    swww img -t any --transition-bezier 0.0,0.0,1.0,1.0 --transition-duration .8 --transition-step 255 --transition-fps 60 "$BACKGROUND_IMAGE"
}

load_wp
