#!/bin/bash

HASBAT=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "power supply" | cut -d ':' -f2 | xargs)

battery() {
	if [ ! "$HASBAT" = "no" ]; then
		echo $(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "percentage" | cut -d ':' -f2 | xargs | tr -d '%')
	else
		echo "100"
	fi
}
battery_stat() {
	if [ ! "$HASBAT" = "no" ]; then
		echo $(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "state" | cut -d ':' -f2 | xargs | tr -d '%')
	else
		echo "No bat"
	fi
}
time_left() {
	if [ ! "$HASBAT" = "no" ]; then
		echo $(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "percentage" | cut -d ':' -f2 | xargs)
	else
		echo ""
	fi
}

case "$1" in
	--bat) battery;;
	--bat-st) battery_stat;;
	--left) time_left;;
esac
