#!/bin/bash

SINK="@DEFAULT_SINK@"

get_volume() {
  isMute=$(pactl list sinks | grep -C 8 State | grep -C 8 RUNNING | grep Mute | cut -d ':' -f2 | xargs)

	if [[ "$isMute" == "no" ]]; then
    volume=$(pactl list sinks | grep -C 8 State | grep -C 8 RUNNING | grep Volume | cut -d '/' -f2 | xargs | tr -d '%')
		echo "$volume"
	else
		echo "Mute"
	fi
}

get_desc() {
  isRunning=$(pactl list sinks | grep -C 8 State | grep -C 8 RUNNING)

	if [[ "$isRunning" ]]; then
    desc=$(pactl list sinks | grep -C 8 State | grep -C 8 RUNNING | grep Description | cut -d ':' -f2 | xargs)
		echo "$desc"
	else
		echo "Volume"
	fi
}


inc_volume() {
	pactl set-sink-volume $SINK +10%
}

dec_volume() {
	pactl set-sink-volume $SINK -10%
}

toggle_mute() {
	pactl set-sink-mute $SINK toggle
}

if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--desc" ]]; then
	get_desc
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi
