#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# battery notification
$scripts/default/battery_notif &

/home/hiroo/Scripts/wificonnect &

# screen locking when idle
$scripts/default/idle_handler &

# mount HDD
$scripts/mountHdd

# other
fcitx5 -d &

wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
pkill xdg-desktop-portal &

/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-hyprland &

# just pipewire & wireplumber
pipewire &
pipewire-pulse &
wireplumber &
