#!/bin/bash

# variables
config=$HOME/apps-config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# battery notification
"$scripts"/default/battery_notif &

"$HOME"/apps-config/scripts/bin/wifi home &

# screen locking when idle
"$scripts"/default/idle_handler &

# other
fcitx5 -d &

wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
pkill xdg-desktop-portal &

/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-hyprland &

# just pipewire & wireplumber (audio)
pipewire &
pipewire-pulse &
wireplumber &
