#!/bin/bash

# variables
config=$HOME/apps-config/config/hypr

# notification daemon
dunst &

"$HOME"/apps-config/scripts/bin/wifi home &

wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
pkill xdg-desktop-portal &

/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-hyprland &

# just pipewire & wireplumber (audio)
pipewire &
pipewire-pulse &
wireplumber &
