#!/bin/bash

function O() {
  apps=("opera" "obs")
  start_app "${apps[@]}"
}

function start_app() {
  arr=("$@")
  app=$(echo "${arr[*]}" | tr ' ' '\n' | wofi --show dmenu)
  if [ "$app" ]; then
    eval "$app"
  fi
}

case $1 in
  O) O ;;
esac
